import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './Components/Navbar'
import Hobbies from './Objects/Hobbies'
import Me from './Objects/Me'
import Qualifications from './Objects/Qualification'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div>
          <h1>
            Home.Me();
          </h1>
          <Me />
        </div>
        <div>
          <h1>
            Home.Qualifications();
          </h1>
          <Qualifications />
        </div>
        <div>
          <h1>
            Home.Hobbies();
          </h1>
          <Hobbies />
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/PATEL96"
          target="_blank"
          rel="noopener noreferrer"
        >
          Maintained by{' '}
          <span className={styles.logo}>
            PATEL96
          </span>
        </a>
      </footer>
    </div>
  )
}
